version: '3.2'

services:
    web:
      container_name: brasilio_web
      env_file: .env
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - DEV_BUILD=true
      volumes:
        - .:/app
        - ./docker/data/app:/data
      ports:
        - 4200:5000
      depends_on:
        - db
        - mail
        - redis

    db:
      image: postgres:11.3
      container_name: brasilio_postgres
      env_file: .env
      shm_size: 256m
      volumes:
        - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
        - ./docker/data/postgres:/var/lib/postgresql/data
      command: -c "config_file=/etc/postgresql/postgresql.conf"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        retries: 3

    mail:
      image: mailhog/mailhog
      container_name: brasilio_mailhog
      env_file: .env
      ports:
        - "4201:8025"

    redis:
      image: redis:alpine
      container_name: brasilio_redis
      env_file: .env
      volumes:
        - "./docker/data/redis:/data"
