version: '3.2'

services:
    web:
      env_file: .env
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - DEV_BUILD=true
      volumes:
        - .:/app
        - ./docker/data/web:/data
      ports:
        - 4200:5000
      depends_on:
        - db
        - mail
        - redis

    db:
      image: postgres:11.3
      env_file: .env
      shm_size: 256m
      volumes:
        - ./docker/postgresql.dev.conf:/etc/postgresql/postgresql.conf
        - ./docker/data/db:/var/lib/postgresql/data
      command: -c "config_file=/etc/postgresql/postgresql.conf"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        retries: 3

    redis:
      image: redis:alpine
      env_file: .env
      volumes:
        - ./docker/data/redis:/data

    mail:
      image: mailhog/mailhog
      env_file: .env
      ports:
        - "4201:8025"
